export type Category = "all" | "pastries" | "cakes" | "bread" | "cookies";

export interface Product {
  id: string;
  name: string;
  description: string;
  price: string;
  image: string;
  category: Category;
}

export const categories = [
  { slug: "all", name: "All Products" },
  { slug: "pastries", name: "Pastries" },
  { slug: "cakes", name: "Cakes" },
  { slug: "bread", name: "Bread" },
  { slug: "cookies", name: "Cookies" },
];

export const products: Product[] = [
  // Pastries
  {
    id: "pastry_01",
    name: "Classic Croissant",
    description: "Buttery, flaky layers of perfection",
    price: "£3.50",
    image: "/images/products/pastry_01.jpg",
    category: "pastries",
  },
  {
    id: "pastry_02",
    name: "Almond Danish",
    description: "Sweet almond filling in crisp pastry",
    price: "£4.25",
    image: "/images/products/pastry_02.jpg",
    category: "pastries",
  },
  {
    id: "pastry_03",
    name: "Pain au Chocolat",
    description: "Dark chocolate wrapped in golden pastry",
    price: "£3.75",
    image: "/images/products/pastry_03.jpg",
    category: "pastries",
  },
  {
    id: "pastry_04",
    name: "Apple Turnover",
    description: "Warm spiced apples in flaky pastry",
    price: "£3.25",
    image: "/images/products/pastry_04.jpg",
    category: "pastries",
  },
  {
    id: "pastry_05",
    name: "Cinnamon Roll",
    description: "Soft swirls with cinnamon sugar",
    price: "£3.95",
    image: "/images/products/pastry_05.jpg",
    category: "pastries",
  },
  {
    id: "pastry_06",
    name: "Fruit Danish",
    description: "Seasonal fruit on vanilla custard",
    price: "£4.50",
    image: "/images/products/pastry_06.jpg",
    category: "pastries",
  },
  {
    id: "pastry_07",
    name: "Éclair",
    description: "Choux pastry filled with cream",
    price: "£4.75",
    image: "/images/products/pastry_07.jpg",
    category: "pastries",
  },
  {
    id: "pastry_08",
    name: "Palmier",
    description: "Caramelized puff pastry hearts",
    price: "£2.95",
    image: "/images/products/pastry_08.jpg",
    category: "pastries",
  },
  {
    id: "pastry_09",
    name: "Bear Claw",
    description: "Almond-filled pastry with sliced almonds",
    price: "£4.25",
    image: "/images/products/pastry_09.jpg",
    category: "pastries",
  },
  {
    id: "pastry_10",
    name: "Custard Tart",
    description: "Silky vanilla custard in crisp shell",
    price: "£3.50",
    image: "/images/products/pastry_10.jpg",
    category: "pastries",
  },
  {
    id: "pastry_11",
    name: "Scone",
    description: "Traditional British teatime treat",
    price: "£2.75",
    image: "/images/products/pastry_11.jpg",
    category: "pastries",
  },
  {
    id: "pastry_12",
    name: "Profiterole",
    description: "Cream puff with chocolate drizzle",
    price: "£3.25",
    image: "/images/products/pastry_12.jpg",
    category: "pastries",
  },
  {
    id: "pastry_13",
    name: "Mille-feuille",
    description: "Napoleon with layers of cream",
    price: "£5.25",
    image: "/images/products/pastry_13.jpg",
    category: "pastries",
  },

  // Cakes
  {
    id: "cake_01",
    name: "Chocolate Fudge Cake",
    description: "Rich chocolate layers with fudge frosting",
    price: "from £28/kg",
    image: "/images/products/cake_01.jpg",
    category: "cakes",
  },
  {
    id: "cake_02",
    name: "Victoria Sponge",
    description: "Classic British cake with jam & cream",
    price: "from £22/kg",
    image: "/images/products/cake_02.jpg",
    category: "cakes",
  },
  {
    id: "cake_03",
    name: "Red Velvet Cake",
    description: "Velvety texture with cream cheese frosting",
    price: "from £32/kg",
    image: "/images/products/cake_03.jpg",
    category: "cakes",
  },
  {
    id: "cake_04",
    name: "Lemon Drizzle Cake",
    description: "Zesty lemon cake with sweet glaze",
    price: "from £24/kg",
    image: "/images/products/cake_04.jpg",
    category: "cakes",
  },
  {
    id: "cake_05",
    name: "Carrot Cake",
    description: "Spiced cake with cream cheese frosting",
    price: "from £26/kg",
    image: "/images/products/cake_05.jpg",
    category: "cakes",
  },
  {
    id: "cake_06",
    name: "Black Forest Gateau",
    description: "Chocolate, cherries & whipped cream",
    price: "from £35/kg",
    image: "/images/products/cake_06.png",
    category: "cakes",
  },
  {
    id: "cake_07",
    name: "Strawberry Shortcake",
    description: "Fresh strawberries & vanilla cream",
    price: "from £30/kg",
    image: "/images/products/cake_07.jpg",
    category: "cakes",
  },
  {
    id: "cake_08",
    name: "Tiramisu Cake",
    description: "Coffee-soaked layers with mascarpone",
    price: "from £38/kg",
    image: "/images/products/cake_08.jpg",
    category: "cakes",
  },
  {
    id: "cake_09",
    name: "Banana Cake",
    description: "Moist banana cake with buttercream",
    price: "from £23/kg",
    image: "/images/products/cake_09.jpg",
    category: "cakes",
  },
  {
    id: "cake_10",
    name: "Cheesecake",
    description: "Creamy New York style cheesecake",
    price: "from £34/kg",
    image: "/images/products/cake_10.jpg",
    category: "cakes",
  },
  {
    id: "cake_11",
    name: "Rainbow Cake",
    description: "Colorful layers with vanilla buttercream",
    price: "from £36/kg",
    image: "/images/products/cake_11.jpg",
    category: "cakes",
  },
  {
    id: "cake_12",
    name: "Coffee Walnut Cake",
    description: "Coffee sponge with walnut buttercream",
    price: "from £27/kg",
    image: "/images/products/cake_12.jpg",
    category: "cakes",
  },
  {
    id: "cake_13",
    name: "Chocolate Orange Cake",
    description: "Rich chocolate with orange zest",
    price: "from £29/kg",
    image: "/images/products/cake_13.jpg",
    category: "cakes",
  },
  {
    id: "cake_14",
    name: "Funfetti Cake",
    description: "Vanilla cake with rainbow sprinkles",
    price: "from £25/kg",
    image: "/images/products/cake_14.jpg",
    category: "cakes",
  },
  {
    id: "cake_15",
    name: "Lemon Meringue Cake",
    description: "Lemon cake with meringue topping",
    price: "from £31/kg",
    image: "/images/products/cake_15.jpg",
    category: "cakes",
  },

  // Bread
  {
    id: "bread_01",
    name: "Artisan Sourdough",
    description: "Traditional sourdough with crispy crust",
    price: "£4.50",
    image: "/images/products/bread_01.jpg",
    category: "bread",
  },
  {
    id: "bread_02",
    name: "French Baguette",
    description: "Classic French bread with golden crust",
    price: "£2.95",
    image: "/images/products/bread_02.jpg",
    category: "bread",
  },
  {
    id: "bread_03",
    name: "Whole Wheat Loaf",
    description: "Healthy whole grain bread",
    price: "£3.75",
    image: "/images/products/bread_03.png",
    category: "bread",
  },
  {
    id: "bread_04",
    name: "Rye Bread",
    description: "Dense, flavorful rye with caraway seeds",
    price: "£4.25",
    image: "/images/products/bread_04.jpg",
    category: "bread",
  },
  {
    id: "bread_05",
    name: "Focaccia",
    description: "Italian flatbread with herbs & olive oil",
    price: "£3.50",
    image: "/images/products/bread_05.jpg",
    category: "bread",
  },
  {
    id: "bread_06",
    name: "Ciabatta",
    description: "Rustic Italian bread with large holes",
    price: "£3.25",
    image: "/images/products/bread_06.jpg",
    category: "bread",
  },

  // Cookies
  {
    id: "cookies_01",
    name: "Chocolate Chip Cookies",
    description: "Classic cookies with chocolate chips",
    price: "from £18/kg",
    image: "/images/products/cookies_01.jpg",
    category: "cookies",
  },
  {
    id: "cookies_02",
    name: "Oatmeal Raisin Cookies",
    description: "Chewy oats with sweet raisins",
    price: "from £16/kg",
    image: "/images/products/cookies_02.jpg",
    category: "cookies",
  },
  {
    id: "cookies_03",
    name: "Sugar Cookies",
    description: "Sweet, soft cookies with sugar crystals",
    price: "from £15/kg",
    image: "/images/products/cookies_03.jpg",
    category: "cookies",
  },
  {
    id: "cookies_04",
    name: "Double Chocolate Cookies",
    description: "Rich chocolate cookies with chocolate chips",
    price: "from £20/kg",
    image: "/images/products/cookies_04.jpg",
    category: "cookies",
  },
  {
    id: "cookies_05",
    name: "Ginger Snaps",
    description: "Spiced cookies with crystallized ginger",
    price: "from £17/kg",
    image: "/images/products/cookies_05.jpg",
    category: "cookies",
  },
  {
    id: "cookies_06",
    name: "Shortbread",
    description: "Buttery Scottish shortbread cookies",
    price: "from £22/kg",
    image: "/images/products/cookies_06.jpg",
    category: "cookies",
  },
];